// Generated by `pnpm tokens:build` — do not edit by hand.
import 'package:flutter/material.dart';

class DSColors {
  DSColors._();

  // Surface
  static const Color surfaceL0 = Color(0xFFFFFFFF);
  static const Color surfaceL1 = Color(0xFFF9F9F9);
  static const Color surfaceL2 = Color(0xFFF2F2F2);
  static const Color surfaceL3 = Color(0xFFE8E8E8);
  static const Color surfaceL4 = Color(0xFFD9D9D9);
  static const Color surfaceL5 = Color(0xFFC4C4C4);
  static const Color surfaceL6 = Color(0xFFA0A0A0);

  // Text
  static const Color textPrimary   = Color(0xFF111111);
  static const Color textSecondary = Color(0xFF555555);
  static const Color textTertiary  = Color(0xFF888888);
  static const Color textDisabled  = Color(0xFFB0B0B0);
  static const Color textBrand     = Color(0xFF0052CC);
  static const Color textLink      = Color(0xFF0065FF);
  static const Color textError     = Color(0xFFD32F2F);
  static const Color textAlert     = Color(0xFFE65100);
  static const Color textInfo      = Color(0xFF0277BD);
  static const Color textSuccess   = Color(0xFF2E7D32);

  // Border
  static const Color borderPrimary  = Color(0xFF111111);
  static const Color borderSubtle   = Color(0xFFE0E0E0);
  static const Color borderBrand    = Color(0xFF0052CC);
  static const Color borderError    = Color(0xFFD32F2F);
  static const Color borderAlert    = Color(0xFFE65100);
  static const Color borderInfo     = Color(0xFF0277BD);
  static const Color borderSuccess  = Color(0xFF2E7D32);
  static const Color borderDisabled = Color(0xFFB0B0B0);
  static const Color borderSelected = Color(0xFF0052CC);
}
