import type { Meta, StoryObj } from '@storybook/react-vite';
import React from 'react';
import { StatusChip } from './StatusChip';

const meta = {
  title: 'Components/StatusChip',
  component: StatusChip,
  tags: ['autodocs'],
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: `
Status Chips are a read-only variation of Chips that are auto-generated by the system based on specific criteria. Unlike regular Chips, they are **not dismissable** and display a fixed icon and label per status type.

**Types**
- **At Risk** — flags an item that may not meet a goal or deadline (alert/yellow)
- **Excluded** — marks an item that has been deliberately removed from a set (error/red)

**Usage guidance**
- Use in tables, list rows, and detail panels to surface automated status signals
- Always system-generated — do not use for user-applied tags (use Chip instead)
        `.trim(),
      },
    },
  },
  argTypes: {
    type: { control: 'select', options: ['at-risk', 'excluded'] },
    size: { control: 'select', options: ['md', 'sm'] },
  },
  args: {
    type: 'at-risk',
    size: 'md',
  },
} satisfies Meta<typeof StatusChip>;

export default meta;
type Story = StoryObj<typeof meta>;

// ─── Playground ──────────────────────────────────────────────────────────────

export const Playground: Story = {};

// ─── All Variants ─────────────────────────────────────────────────────────────

export const AllVariants: Story = {
  name: 'All Variants',
  parameters: {
    controls: { disable: true },
    docs: {
      description: { story: 'Both types in both sizes.' },
    },
  },
  render: () => (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      {(['md', 'sm'] as const).map(size => (
        <div key={size} style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          <span style={{ fontSize: 11, fontFamily: 'monospace', color: 'var(--ds-color-text-tertiary)' }}>
            {size === 'md' ? 'Default' : 'Small'}
          </span>
          <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
            <StatusChip type="at-risk" size={size} />
            <StatusChip type="excluded" size={size} />
          </div>
        </div>
      ))}
    </div>
  ),
};

// ─── In Context ───────────────────────────────────────────────────────────────

const GOALS = [
  { name: 'Q2 Revenue Target',   owner: 'Sales',     progress: '64%',  status: 'at-risk'  },
  { name: 'Customer NPS ≥ 50',   owner: 'CX',        progress: '91%',  status: null       },
  { name: 'Reduce Churn < 2%',   owner: 'Growth',    progress: '38%',  status: 'excluded' },
  { name: 'Launch Mobile App',   owner: 'Product',   progress: '78%',  status: 'at-risk'  },
  { name: 'Hire 10 Engineers',   owner: 'Recruiting', progress: '100%', status: null       },
] as const;

const thStyle: React.CSSProperties = {
  padding: '8px 16px',
  textAlign: 'left',
  fontSize: 12,
  fontWeight: 600,
  color: 'var(--ds-color-text-secondary)',
  borderBottom: '1px solid var(--ds-color-border-subtle)',
};

const tdStyle: React.CSSProperties = {
  padding: '10px 16px',
  fontSize: 14,
  color: 'var(--ds-color-text-primary)',
  fontFamily: 'var(--ds-font-family-body)',
};

export const InContext: Story = {
  name: 'In Context',
  parameters: {
    controls: { disable: true },
    layout: 'padded',
    docs: {
      description: { story: 'Status Chips shown in a goals tracking table — typical system-generated usage.' },
    },
  },
  render: () => (
    <div style={{ minWidth: 520, borderRadius: 12, border: '1px solid var(--ds-color-border-subtle)', overflow: 'hidden' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'var(--ds-font-family-body)' }}>
        <thead>
          <tr>
            <th style={thStyle}>Goal</th>
            <th style={thStyle}>Owner</th>
            <th style={thStyle}>Progress</th>
            <th style={thStyle}>Status</th>
          </tr>
        </thead>
        <tbody>
          {GOALS.map((goal, i) => (
            <tr key={goal.name}>
              <td style={{ ...tdStyle, fontWeight: 600, borderBottom: i < GOALS.length - 1 ? '1px solid var(--ds-color-border-subtle)' : 'none' }}>{goal.name}</td>
              <td style={{ ...tdStyle, color: 'var(--ds-color-text-secondary)', borderBottom: i < GOALS.length - 1 ? '1px solid var(--ds-color-border-subtle)' : 'none' }}>{goal.owner}</td>
              <td style={{ ...tdStyle, borderBottom: i < GOALS.length - 1 ? '1px solid var(--ds-color-border-subtle)' : 'none' }}>{goal.progress}</td>
              <td style={{ ...tdStyle, borderBottom: i < GOALS.length - 1 ? '1px solid var(--ds-color-border-subtle)' : 'none' }}>
                {goal.status ? <StatusChip type={goal.status} size="sm" /> : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  ),
};
