// Generated by `pnpm tokens:build` — do not edit by hand.

class DSSpacing {
  DSSpacing._();

  static const double x3s =  2;
  static const double x2s =  4;
  static const double xs  =  6;
  static const double s   =  8;
  static const double m   = 12;
  static const double l   = 16;
  static const double xl  = 24;
  static const double x2l = 32;
  static const double x3l = 40;
  static const double x4l = 48;
  static const double x5l = 56;
  static const double x6l = 64;
}

class DSBorderRadius {
  DSBorderRadius._();

  static const double xs   =  4;
  static const double s    =  8;
  static const double m    = 12;
  static const double l    = 16;
  static const double pill = 999;
}

class DSBorderWidth {
  DSBorderWidth._();

  static const double xs = 1;
  static const double s  = 1.5;
  static const double m  = 2;
  static const double l  = 4;
  static const double xl = 8;
}
