// Generated by `pnpm tokens:build` — do not edit by hand.
import 'package:flutter/material.dart';

class DSFontSize {
  DSFontSize._();

  // Body
  static const double body2xs = 10;
  static const double bodyXs  = 11;
  static const double bodyS   = 12;
  static const double bodyM   = 14;
  static const double bodyL   = 16;
  static const double bodyXl  = 18;
  static const double body2xl = 20;

  // Button
  static const double buttonS  = 12;
  static const double buttonM  = 14;
  static const double buttonL  = 16;
  static const double buttonXl = 18;
}

class DSFontWeight {
  DSFontWeight._();

  static const FontWeight regular = FontWeight.w400;
  static const FontWeight medium  = FontWeight.w500;
  static const FontWeight bold    = FontWeight.w700;
}

class DSLetterSpacing {
  DSLetterSpacing._();

  static const double buttonTab = 0.14; // 0.01em at 14px base
}
