import StyleDictionary from 'style-dictionary';

// ---------------------------------------------------------------------------
// Custom transforms
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  filter: (token) => token.$type === 'dimension',
  transform: (token) => token.$value,
});

StyleDictionary.registerTransform({
  name: 'fontWeight/css',
  type: 'value',
  filter: (token) => token.$type === 'fontWeight',
  transform: (token) => token.$value,
});

StyleDictionary.registerTransform({
  name: 'size/dart',
  type: 'value',
  filter: (token) => token.$type === 'dimension',
  transform: (token) => String(parseFloat(token.$value)),
});

// ---------------------------------------------------------------------------
// Custom transform groups
// ---------------------------------------------------------------------------

StyleDictionary.registerTransformGroup({
  name: 'css/ds',
  transforms: [
    'attribute/cti',
    'name/kebab',
    'color/css',
    'size/px',
    'fontFamily/css',
    'fontWeight/css',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'flutter/dart',
  transforms: [
    'name/camel',
    'size/dart',
  ],
});

// ---------------------------------------------------------------------------
// Helpers shared by both Dart formats
// ---------------------------------------------------------------------------

function hexToFlutterColor(hex) {
  const clean = hex.replace('#', '');
  const full = clean.length === 3
    ? clean.split('').map((c) => c + c).join('')
    : clean;
  if (full.length === 8) {
    // RRGGBBAA → Flutter Color(0xAARRGGBB)
    const rr = full.slice(0, 2).toUpperCase();
    const gg = full.slice(2, 4).toUpperCase();
    const bb = full.slice(4, 6).toUpperCase();
    const aa = full.slice(6, 8).toUpperCase();
    return `const Color(0x${aa}${rr}${gg}${bb})`;
  }
  return `const Color(0xFF${full.toUpperCase()})`;
}

const fontWeightMap = {
  '400': 'FontWeight.w400',
  '500': 'FontWeight.w500',
  '600': 'FontWeight.w600',
  '700': 'FontWeight.w700',
  '800': 'FontWeight.w800',
  '900': 'FontWeight.w900',
};

function tokenToDartLine(token, className) {
  const name = token.name;
  const type = token.$type;
  const raw = token.value ?? token.$value;

  let dartType, dartValue;

  switch (type) {
    case 'color':
      dartType  = 'Color';
      dartValue = hexToFlutterColor(String(raw));
      break;
    case 'dimension':
      dartType  = 'double';
      dartValue = String(parseFloat(raw));
      break;
    case 'fontWeight':
      dartType  = 'FontWeight';
      dartValue = fontWeightMap[String(raw)] ?? `FontWeight.w${raw}`;
      break;
    case 'fontFamily':
      dartType  = 'String';
      dartValue = `'${raw}'`;
      break;
    default:
      dartType  = 'String';
      dartValue = `'${raw}'`;
  }

  return `  static const ${dartType} ${name} = ${dartValue};`;
}

// ---------------------------------------------------------------------------
// Custom formats
// ---------------------------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'flutter/dart-tokens',
  format: ({ dictionary }) => {
    const lines = [
      '// Generated by Style Dictionary — do not edit by hand.',
      '// Run `npm run build` in the tokens/ folder to regenerate.',
      '',
      "import 'package:flutter/material.dart';",
      '',
      '// ignore_for_file: non_constant_identifier_names',
      '',
      'class DSTokens {',
      '  DSTokens._();',
      '',
    ];
    for (const token of dictionary.allTokens) {
      lines.push(tokenToDartLine(token));
    }
    lines.push('}');
    lines.push('');
    return lines.join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'flutter/dart-tokens-dark',
  format: ({ dictionary }) => {
    const lines = [
      '// Generated by Style Dictionary — do not edit by hand.',
      '// Run `npm run build` in the tokens/ folder to regenerate.',
      '',
      "import 'package:flutter/material.dart';",
      '',
      '// ignore_for_file: non_constant_identifier_names',
      '',
      'class DSTokensDark {',
      '  DSTokensDark._();',
      '',
    ];
    for (const token of dictionary.allTokens) {
      lines.push(tokenToDartLine(token));
    }
    lines.push('}');
    lines.push('');
    return lines.join('\n');
  },
});

// ---------------------------------------------------------------------------
// Light build
// ---------------------------------------------------------------------------

const sd = new StyleDictionary({
  usesDtcg: true,
  log: { verbosity: 'default' },
  source: ['foundationColors.json', 'colors.json', 'spacing.json', 'typography.json', 'semanticTypography.json'],
  platforms: {
    css: {
      transformGroup: 'css/ds',
      prefix: 'ds',
      buildPath: '../packages/react/ds-react/src/tokens/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
        },
      ],
    },
    flutter: {
      transformGroup: 'flutter/dart',
      buildPath: '../packages/flutter/ds_flutter/lib/src/tokens/',
      files: [
        {
          destination: 'ds_tokens.dart',
          format: 'flutter/dart-tokens',
        },
      ],
    },
  },
});

// ---------------------------------------------------------------------------
// Dark build — only semantic color tokens change between modes
// ---------------------------------------------------------------------------

const sdDark = new StyleDictionary({
  usesDtcg: true,
  log: { verbosity: 'default' },
  source: ['foundationColors.json', 'colorsDark.json', 'spacing.json', 'typography.json', 'semanticTypography.json'],
  platforms: {
    'css-dark': {
      transformGroup: 'css/ds',
      prefix: 'ds',
      buildPath: '../packages/react/ds-react/src/tokens/',
      files: [
        {
          destination: 'tokens-dark.css',
          format: 'css/variables',
          options: {
            selector: '[data-theme="dark"]',
          },
        },
      ],
    },
    'flutter-dark': {
      transformGroup: 'flutter/dart',
      buildPath: '../packages/flutter/ds_flutter/lib/src/tokens/',
      files: [
        {
          destination: 'ds_tokens_dark.dart',
          format: 'flutter/dart-tokens-dark',
          filter: (token) => token.path[0] === 'color',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
await sdDark.buildAllPlatforms();
